In [3]:
import pandas as pd

pd.set_option("display.max_columns", None)

fraud = pd.read_csv( "../data/processed/fraud_merged.csv" ) 
fraud.head()

,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,sex,age,ip_address,class,lower_bound_ip_address,upper_bound_ip_address,country,time_since_signup,hour_of_day,day_of_week,transaction_count,device_transaction_count,prev_purchase,time_between_transactions
0,2,2015-01-11 03:47:13,2015-02-21 10:03:37,54,FGBQNDNBETFJJ,SEO,Chrome,F,25,880217484,0,8.724152e+08,8.891924e+08,United States,3564984.0,10,5,1,1,NaN,0.0
1,4,2015-06-02 16:40:57,2015-09-26 21:32:16,41,MKFUIVOHLJBYN,Direct,Safari,F,38,2785906106,0,2.785542e+09,2.786066e+09,Switzerland,10039879.0,21,5,1,1,NaN,0.0
2,8,2015-05-28 07:53:06,2015-08-13 11:53:07,47,SCQGQALXBUQZJ,SEO,Chrome,M,25,356056736,0,3.523215e+08,3.690988e+08,United States,6667201.0,11,3,1,1,NaN,0.0
3,12,2015-01-10 06:25:12,2015-03-04 20:56:37,35,MSNWCFEHKTIOY,Ads,Safari,M,19,2985180352,0,2.985034e+09,2.985296e+09,Mexico,4631485.0,20,2,1,1,NaN,0.0
4,16,2015-02-03 13:48:23,2015-03-12 12:46:23,9,FROZWSSWOHZBE,Direct,IE,M,32,578312545,0,5.704253e+08,5.872026e+08,United States,3193080.0,12,3,1,1,NaN,0.0

In [4]:
fraud[[ "time_since_signup", "hour_of_day", "day_of_week", "transaction_count", "device_transaction_count", "time_between_transactions" ]].head()

,time_since_signup,hour_of_day,day_of_week,transaction_count,device_transaction_count,time_between_transactions
0,3564984.0,10,5,1,1,0.0
1,10039879.0,21,5,1,1,0.0
2,6667201.0,11,3,1,1,0.0
3,4631485.0,20,2,1,1,0.0
4,3193080.0,12,3,1,1,0.0

In [5]:
fraud["time_since_signup"].describe()

count    1.291460e+05
mean     4.927250e+06
std      3.129629e+06
min      1.000000e+00
25%      2.180227e+06
50%      4.925322e+06
75%      7.643550e+06
max      1.036797e+07
Name: time_since_signup, dtype: float64

In [6]:
fraud["hour_of_day"].value_counts().sort_index()

hour_of_day
0     5284
1     5308
2     5456
3     5565
4     5189
5     5266
6     5485
7     5311
8     5435
9     5524
10    5216
11    5389
12    5419
13    5365
14    5465
15    5432
16    5428
17    5517
18    5347
19    5385
20    5259
21    5313
22    5435
23    5353
Name: count, dtype: int64

In [8]:
fraud["day_of_week"].value_counts().sort_index()

day_of_week
0    18565
1    18204
2    18159
3    18442
4    18374
5    18556
6    18846
Name: count, dtype: int64

In [7]:
fraud["transaction_count"].describe()

count    129146.0
mean          1.0
std           0.0
min           1.0
25%           1.0
50%           1.0
75%           1.0
max           1.0
Name: transaction_count, dtype: float64

In [10]:
fraud["device_transaction_count"].describe()

count    129146.000000
mean          1.689669
std           2.653866
min           1.000000
25%           1.000000
50%           1.000000
75%           1.000000
max          20.000000
Name: device_transaction_count, dtype: float64

In [9]:
fraud["time_between_transactions"].describe()

count    129146.0
mean          0.0
std           0.0
min           0.0
25%           0.0
50%           0.0
75%           0.0
max           0.0
Name: time_between_transactions, dtype: float64

In [11]:
fraud["class"].value_counts()
fraud["class"].value_counts(normalize=True) * 100

class
0    90.500674
1     9.499326
Name: proportion, dtype: float64

Feature Description

1. time_since_signup
   Time between registration and purchase.

2. hour_of_day
   Purchase hour.

3. day_of_week
   Day purchase occurred.

4. transaction_count
   Number of transactions by user.

5. device_transaction_count
   Number of transactions from device.

6. time_between_transactions
   Transaction velocity indicator.